### ISSUE TITLE
multiple hosts for callback - same agent

### ISSUE THREAD

**Issue by EdwardDali** [MythicAgents/Athena#48]
Hi,

Is there any way to add multiple hosts for callback for the same agent? also is there any way to add multiple communication channels and ports such as http and https for the same agent?
such as http://domain1.com:80,http://domain2.org:80, https://domain1.com:443,https://domain2.com:8080

Thank you

**Comment by checkymander** [comment]
Hey sorry for the delay. I completely missed this.

As of right now it's not supported due to it not being an "official" feature of the Mythic HTTP profile. It might be worth heading over to https://github.com/MythicC2Profiles/http and making it a feature request for the profile, so I can officially support it!
